// ============================================================
//  dom/node.rs  —  DOM tree types
// ============================================================
//
//  A stripped-down but faithful representation of the W3C DOM.
//
//  Key design decisions:
//   • Children are stored as owned Vec<Node> (no arena, no Rc<RefCell<>>)
//     This keeps the API simple for Phase 1; an arena can be swapped in
//     later without changing public types.
//   • Attributes are stored as a plain Vec to preserve document order,
//     with an O(n) lookup helper (fine for small attribute lists).
//   • `NodeType` carries the payload so we avoid heap-boxing common cases.

use std::fmt;

/// The type-specific payload of a DOM node.
#[derive(Debug, Clone)]
pub enum NodeType {
    /// The invisible root of the document tree.
    Document,
    /// A tagged element: `<div class="foo">`.
    Element(ElementData),
    /// A text run between tags.
    Text(String),
    /// An HTML comment: `<!-- ... -->`.
    Comment(String),
    /// A DOCTYPE declaration: `<!DOCTYPE html>`.
    Doctype(String),
}

/// A process-unique element identity.
///
/// DOM paths shift whenever the tree is restructured, so anything that has to
/// remember *which element* across mutations — focus, form-control state —
/// keys off this instead.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ElementId(u64);

impl ElementId {
    fn next() -> ElementId {
        use std::sync::atomic::{AtomicU64, Ordering};
        static COUNTER: AtomicU64 = AtomicU64::new(1);
        ElementId(COUNTER.fetch_add(1, Ordering::Relaxed))
    }

    pub fn value(self) -> u64 {
        self.0
    }
}

/// Live state of a form control or option.
///
/// The DOM keeps current state separate from the corresponding content
/// attribute: `None` means the state still mirrors its HTML default. Inputs
/// use `value`/`checked`; `<option>` keeps its local selected bit, while a
/// `<select>` owns the canonical live selection as option-list indexes. Keeping
/// the selection override on the select lets the existing form-reset path drop
/// back to parsed/default selectedness without walking option descendants.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ControlState {
    value: Option<String>,
    checked: Option<bool>,
    selected: Option<bool>,
    selected_indices: Option<Vec<usize>>,
    /// Caret position, counted in characters from the start of the value.
    caret: usize,
}

/// Data stored on an element node.
#[derive(Debug)]
pub struct ElementData {
    /// Lower-cased tag name, e.g. `"div"`.
    pub tag_name: String,
    /// Ordered list of (name, value) attribute pairs.
    pub attributes: Vec<(String, String)>,
    /// Stable identity, minted per element.
    id: ElementId,
    /// Present once this element has live form/option state.
    control: Option<Box<ControlState>>,
    /// Present once this <canvas> element has a 2D rendering context.
    pub canvas: Option<std::rc::Rc<std::cell::RefCell<crate::canvas::CanvasContext2D>>>,
}

// Cloning an element produces a *new* element, as `cloneNode` does: it gets a
// fresh identity rather than aliasing the original.
impl Clone for ElementData {
    fn clone(&self) -> Self {
        Self {
            tag_name: self.tag_name.clone(),
            attributes: self.attributes.clone(),
            id: ElementId::next(),
            control: self.control.clone(),
            canvas: self.canvas.clone(),
        }
    }
}

impl ElementData {
    pub fn new(tag_name: impl Into<String>, attributes: Vec<(String, String)>) -> Self {
        Self {
            tag_name: tag_name.into(),
            attributes,
            id: ElementId::next(),
            control: None,
            canvas: None,
        }
    }

    /// Get or lazily create the 2D rendering context for this canvas element.
    pub fn canvas_context(&mut self) -> std::rc::Rc<std::cell::RefCell<crate::canvas::CanvasContext2D>> {
        if let Some(c) = &self.canvas {
            return c.clone();
        }
        let w = self
            .get_attr("width")
            .and_then(|s| s.trim().trim_end_matches("px").parse::<u32>().ok())
            .unwrap_or(300);
        let h = self
            .get_attr("height")
            .and_then(|s| s.trim().trim_end_matches("px").parse::<u32>().ok())
            .unwrap_or(150);
        let ctx = std::rc::Rc::new(std::cell::RefCell::new(crate::canvas::CanvasContext2D::new(w, h)));
        self.canvas = Some(ctx.clone());
        ctx
    }

    /// The raster image generated by this canvas, if it has a context.
    pub fn canvas_image(&self) -> Option<std::rc::Rc<crate::image::RasterImage>> {
        self.canvas.as_ref().map(|c| c.borrow().to_raster_image())
    }

    /// This element's stable identity.
    pub fn element_id(&self) -> ElementId {
        self.id
    }

    /// Look up an attribute value by name (case-insensitive).
    pub fn get_attr(&self, name: &str) -> Option<&str> {
        self.attributes
            .iter()
            .find(|(k, _)| k.eq_ignore_ascii_case(name))
            .map(|(_, v)| v.as_str())
    }

    /// Set or update an attribute value by name.
    pub fn set_attr(&mut self, name: &str, val: &str) {
        if let Some((_, v)) = self
            .attributes
            .iter_mut()
            .find(|(k, _)| k.eq_ignore_ascii_case(name))
        {
            *v = val.to_string();
        } else {
            self.attributes.push((name.to_string(), val.to_string()));
        }
    }

    /// Remove an attribute by name.
    pub fn remove_attr(&mut self, name: &str) {
        self.attributes
            .retain(|(k, _)| !k.eq_ignore_ascii_case(name));
    }

    // ── Form controls ───────────────────────────────────────────────────────

    /// The `type` of an `<input>`, lower-cased, defaulting to `text`.
    pub fn input_type(&self) -> String {
        self.get_attr("type")
            .map(|t| t.trim().to_ascii_lowercase())
            .unwrap_or_else(|| "text".to_string())
    }

    /// True for elements that hold a user-editable text value.
    pub fn is_text_entry(&self) -> bool {
        match self.tag_name.as_str() {
            "textarea" => true,
            "input" => matches!(
                self.input_type().as_str(),
                "text" | "search" | "url" | "tel" | "email" | "password" | "number"
            ),
            _ => false,
        }
    }

    /// True for the two checkable input types.
    pub fn is_checkable(&self) -> bool {
        self.tag_name == "input" && matches!(self.input_type().as_str(), "checkbox" | "radio")
    }

    /// True for any element that participates in form submission.
    pub fn is_form_control(&self) -> bool {
        matches!(
            self.tag_name.as_str(),
            "input" | "textarea" | "select" | "button"
        )
    }

    pub fn is_disabled(&self) -> bool {
        self.get_attr("disabled").is_some()
    }

    pub fn is_readonly(&self) -> bool {
        self.get_attr("readonly").is_some()
    }

    /// The control's current value: the live one if it has been edited,
    /// otherwise the `value` attribute.
    pub fn control_value(&self) -> String {
        match self.control.as_ref().and_then(|c| c.value.clone()) {
            Some(live) => live,
            None => self.get_attr("value").unwrap_or("").to_string(),
        }
    }

    /// True while the control still mirrors its `value` attribute.
    pub fn value_is_default(&self) -> bool {
        self.control.as_ref().is_none_or(|c| c.value.is_none())
    }

    /// Set the live value, clamping the caret into it.
    pub fn set_control_value(&mut self, value: impl Into<String>) {
        let value = value.into();
        let caret = value.chars().count();
        let control = self.control_mut();
        control.value = Some(value);
        control.caret = control.caret.min(caret);
    }

    /// Drop live control state back to its content-attribute/default state.
    ///
    /// For a `<select>` this also discards its canonical selected-index
    /// override, so the next read once again derives selection from the option
    /// `selected` attributes. This is what lets the generic form-reset loop
    /// restore select defaults without treating `<option>` as form controls.
    pub fn reset_control_value(&mut self) {
        if let Some(control) = self.control.as_mut() {
            control.value = None;
            control.selected_indices = None;
            control.caret = 0;
        }
    }

    /// Current checkedness: the live one if toggled, else the attribute.
    pub fn is_checked(&self) -> bool {
        match self.control.as_ref().and_then(|c| c.checked) {
            Some(live) => live,
            None => self.get_attr("checked").is_some(),
        }
    }

    pub fn set_checked(&mut self, checked: bool) {
        self.control_mut().checked = Some(checked);
    }

    pub fn reset_checked(&mut self) {
        if let Some(control) = self.control.as_mut() {
            control.checked = None;
        }
    }

    /// Current option-local selectedness: live state if changed, otherwise the
    /// boolean `selected` content attribute.
    pub fn is_selected(&self) -> bool {
        match self.control.as_ref().and_then(|c| c.selected) {
            Some(live) => live,
            None => self.get_attr("selected").is_some(),
        }
    }

    /// True while option-local selectedness still mirrors the HTML attribute.
    pub fn selected_is_default(&self) -> bool {
        self.control.as_ref().is_none_or(|c| c.selected.is_none())
    }

    pub fn set_selected(&mut self, selected: bool) {
        self.control_mut().selected = Some(selected);
    }

    pub fn reset_selected(&mut self) {
        if let Some(control) = self.control.as_mut() {
            control.selected = None;
        }
    }

    /// Canonical live selected option indexes for a `<select>`.
    ///
    /// `None` means the selection is pristine and must be derived from option
    /// content attributes (including the single-select first-option fallback).
    /// `Some([])` deliberately represents an explicit all-deselected state.
    pub fn selected_indices(&self) -> Option<&[usize]> {
        self.control
            .as_ref()
            .and_then(|control| control.selected_indices.as_deref())
    }

    pub fn set_selected_indices(&mut self, indices: Vec<usize>) {
        self.control_mut().selected_indices = Some(indices);
    }

    pub fn reset_selected_indices(&mut self) {
        if let Some(control) = self.control.as_mut() {
            control.selected_indices = None;
        }
    }

    /// Caret position in characters, clamped to the current value.
    pub fn caret(&self) -> usize {
        let length = self.control_value().chars().count();
        self.control
            .as_ref()
            .map(|c| c.caret)
            .unwrap_or(0)
            .min(length)
    }

    pub fn set_caret(&mut self, position: usize) {
        let length = self.control_value().chars().count();
        self.control_mut().caret = position.min(length);
    }

    /// True when a placeholder should be shown instead of the value
    /// (drives `:placeholder-shown`).
    pub fn placeholder_shown(&self) -> bool {
        self.get_attr("placeholder").is_some_and(|p| !p.is_empty())
            && self.control_value().is_empty()
    }

    fn control_mut(&mut self) -> &mut ControlState {
        self.control.get_or_insert_with(Box::default)
    }
}

/// A single node in the DOM tree.
#[derive(Debug, Clone)]
pub struct Node {
    pub node_type: NodeType,
    pub children: Vec<Node>,
}

impl Node {
    // ── Constructors ────────────────────────────────────────────────────────

    pub fn document() -> Self {
        Self::leaf(NodeType::Document)
    }

    pub fn element(tag_name: impl Into<String>, attrs: Vec<(String, String)>) -> Self {
        Self::leaf(NodeType::Element(ElementData::new(tag_name, attrs)))
    }

    pub fn text(data: impl Into<String>) -> Self {
        Self::leaf(NodeType::Text(data.into()))
    }

    pub fn comment(data: impl Into<String>) -> Self {
        Self::leaf(NodeType::Comment(data.into()))
    }

    pub fn doctype(name: impl Into<String>) -> Self {
        Self::leaf(NodeType::Doctype(name.into()))
    }

    fn leaf(node_type: NodeType) -> Self {
        Self {
            node_type,
            children: Vec::new(),
        }
    }

    // ── Accessors ───────────────────────────────────────────────────────────

    /// Returns `Some(&ElementData)` if this is an Element node.
    pub fn as_element(&self) -> Option<&ElementData> {
        match &self.node_type {
            NodeType::Element(e) => Some(e),
            _ => None,
        }
    }

    // ── Pretty-printer ──────────────────────────────────────────────────────

    /// Write an indented ASCII tree to `out`.
    ///
    /// Example:
    /// ```text
    /// Document
    /// └── <!DOCTYPE html>
    /// └── html
    ///     ├── head
    ///     │   └── title
    ///     │       └── #text "Hello"
    ///     └── body
    ///         └── p [class="intro"]
    ///             └── #text "World"
    /// ```
    pub fn pretty_print(&self) {
        self.print_recursive("", true, true);
    }

    fn print_recursive(&self, prefix: &str, is_last: bool, is_root: bool) {
        let connector = if is_root {
            ""
        } else if is_last {
            "└── "
        } else {
            "├── "
        };

        let label = self.label();
        println!("{}{}{}", prefix, connector, label);

        let child_prefix = if is_root {
            prefix.to_string()
        } else if is_last {
            format!("{}    ", prefix)
        } else {
            format!("{}│   ", prefix)
        };

        let n = self.children.len();
        for (i, child) in self.children.iter().enumerate() {
            child.print_recursive(&child_prefix, i == n - 1, false);
        }
    }

    /// Short human-readable label for a node.
    fn label(&self) -> String {
        match &self.node_type {
            NodeType::Document => "Document".to_string(),
            NodeType::Doctype(name) => format!("<!DOCTYPE {}>", name),
            NodeType::Element(e) => {
                let mut s = e.tag_name.clone();
                for (k, v) in &e.attributes {
                    s.push_str(&format!(" [{}=\"{}\"]", k, v));
                }
                s
            }
            NodeType::Text(t) => {
                let trimmed = t.trim();
                if trimmed.is_empty() {
                    "#text (whitespace)".to_string()
                } else {
                    format!("#text {:?}", trimmed)
                }
            }
            NodeType::Comment(c) => format!("<!-- {} -->", c.trim()),
        }
    }
}

impl fmt::Display for Node {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.label())
    }
}

// ── Unit tests ───────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn element_data_get_attr() {
        let e = ElementData::new("a", vec![("href".into(), "https://example.com".into())]);
        assert_eq!(e.get_attr("href"), Some("https://example.com"));
        assert_eq!(e.get_attr("HREF"), Some("https://example.com"));
        assert_eq!(e.get_attr("class"), None);
    }

    #[test]
    fn option_selectedness_is_live_and_resettable() {
        let mut option = ElementData::new("option", vec![("selected".into(), String::new())]);
        assert!(option.is_selected());
        assert!(option.selected_is_default());

        option.set_selected(false);
        assert!(!option.is_selected());
        assert!(!option.selected_is_default());
        assert!(option.get_attr("selected").is_some());

        option.reset_selected();
        assert!(option.is_selected());
        assert!(option.selected_is_default());
    }

    #[test]
    fn select_selection_override_is_cleared_by_control_reset() {
        let mut select = ElementData::new("select", Vec::new());
        assert_eq!(select.selected_indices(), None);
        select.set_selected_indices(vec![2, 4]);
        assert_eq!(select.selected_indices(), Some(&[2, 4][..]));
        select.reset_control_value();
        assert_eq!(select.selected_indices(), None);
    }

    #[test]
    fn node_label_element() {
        let n = Node::element("div", vec![("id".into(), "main".into())]);
        assert_eq!(n.label(), r#"div [id="main"]"#);
    }

    #[test]
    fn node_label_text() {
        let n = Node::text("  hello  ");
        assert_eq!(n.label(), r#"#text "hello""#);
    }

    #[test]
    fn node_label_whitespace_text() {
        let n = Node::text("   \n  ");
        assert_eq!(n.label(), "#text (whitespace)");
    }
}
